/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TarefasRouteImport } from './routes/tarefas'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as ProjetosRouteImport } from './routes/projetos'
import { Route as NotificacoesRouteImport } from './routes/notificacoes'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as DocumentosRouteImport } from './routes/documentos'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjetosIdRouteImport } from './routes/projetos.$id'

const TarefasRoute = TarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosRoute = ProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificacoesRoute = NotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentosRoute = DocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosIdRoute = ProjetosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProjetosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/documentos': typeof DocumentosRoute
  '/equipe': typeof EquipeRoute
  '/leads': typeof LeadsRoute
  '/notificacoes': typeof NotificacoesRoute
  '/projetos': typeof ProjetosRouteWithChildren
  '/relatorios': typeof RelatoriosRoute
  '/tarefas': typeof TarefasRoute
  '/projetos/$id': typeof ProjetosIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/documentos': typeof DocumentosRoute
  '/equipe': typeof EquipeRoute
  '/leads': typeof LeadsRoute
  '/notificacoes': typeof NotificacoesRoute
  '/projetos': typeof ProjetosRouteWithChildren
  '/relatorios': typeof RelatoriosRoute
  '/tarefas': typeof TarefasRoute
  '/projetos/$id': typeof ProjetosIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/documentos': typeof DocumentosRoute
  '/equipe': typeof EquipeRoute
  '/leads': typeof LeadsRoute
  '/notificacoes': typeof NotificacoesRoute
  '/projetos': typeof ProjetosRouteWithChildren
  '/relatorios': typeof RelatoriosRoute
  '/tarefas': typeof TarefasRoute
  '/projetos/$id': typeof ProjetosIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/configuracoes'
    | '/documentos'
    | '/equipe'
    | '/leads'
    | '/notificacoes'
    | '/projetos'
    | '/relatorios'
    | '/tarefas'
    | '/projetos/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/configuracoes'
    | '/documentos'
    | '/equipe'
    | '/leads'
    | '/notificacoes'
    | '/projetos'
    | '/relatorios'
    | '/tarefas'
    | '/projetos/$id'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/configuracoes'
    | '/documentos'
    | '/equipe'
    | '/leads'
    | '/notificacoes'
    | '/projetos'
    | '/relatorios'
    | '/tarefas'
    | '/projetos/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DocumentosRoute: typeof DocumentosRoute
  EquipeRoute: typeof EquipeRoute
  LeadsRoute: typeof LeadsRoute
  NotificacoesRoute: typeof NotificacoesRoute
  ProjetosRoute: typeof ProjetosRouteWithChildren
  RelatoriosRoute: typeof RelatoriosRoute
  TarefasRoute: typeof TarefasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tarefas': {
      id: '/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof TarefasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos': {
      id: '/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof ProjetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notificacoes': {
      id: '/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof NotificacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentos': {
      id: '/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof DocumentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/$id': {
      id: '/projetos/$id'
      path: '/$id'
      fullPath: '/projetos/$id'
      preLoaderRoute: typeof ProjetosIdRouteImport
      parentRoute: typeof ProjetosRoute
    }
  }
}

interface ProjetosRouteChildren {
  ProjetosIdRoute: typeof ProjetosIdRoute
}

const ProjetosRouteChildren: ProjetosRouteChildren = {
  ProjetosIdRoute: ProjetosIdRoute,
}

const ProjetosRouteWithChildren = ProjetosRoute._addFileChildren(
  ProjetosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DocumentosRoute: DocumentosRoute,
  EquipeRoute: EquipeRoute,
  LeadsRoute: LeadsRoute,
  NotificacoesRoute: NotificacoesRoute,
  ProjetosRoute: ProjetosRouteWithChildren,
  RelatoriosRoute: RelatoriosRoute,
  TarefasRoute: TarefasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
